import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { Toaster } from "react-hot-toast";
import AppInitializer from "@/components/AppInitializer";
import LayoutControl from "@/app/ClientChildren";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <GoogleOAuthProvider
          clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID}
        >
          <AppInitializer />

          <LayoutControl>{children}</LayoutControl>
        </GoogleOAuthProvider>

        <Toaster
          position="bottom-center"
          toastOptions={{
            style: {
              background: "#654321",
              color: "white",
              borderRadius: "8px",
              fontSize: "14px",
            },
          }}
        />
      </body>
    </html>
  );
}
