import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { Toaster } from "react-hot-toast";
import NavBar from "@/components/Layouts/NavBar";
import Footer from "@/components/Layouts/Footer";
import { getUserFromCookie, isLoggedIn } from "@/lib/auth";
import { getCookie } from "cookies-next";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import AppInitializer from "@/components/AppInitializer";
// import ProtectedPage from "@/components/Layouts/ProtectedPage";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const cookieStore = await cookies();
  const token = cookieStore.get("auth")?.value;

  return (
    <html lang="en">
      <body>
        {/* <Toaster /> */}
        {/* <NavBar /> */}
        <GoogleOAuthProvider
          clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID}
        >
          {token ? (
            <>
              <NavBar />
              <AppInitializer />
              {children}
              <Footer />
            </>
          ) : (
            <>{children}</>
          )}
        </GoogleOAuthProvider>
        {/* <Footer /> */}
        <Toaster
          position="bottom-center"
          toastOptions={{
            style: {
              background: "#654321",
              color: "white",
              borderRadius: "8px",
              fontSize: "14px",
            },
          }}
        />
      </body>
    </html>
  );
}
